

# docker run --name raspbian -it schachr/raspbian-stretch:latest /bin/bash

sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull sedden/rpi-raspbian-qemu
- docker ps -a

before_script:
  - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
  - echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' | sudo tee -a /proc/sys/fs/binfmt_misc/register

script:
  - docker run --rm -i -t sedden/rpi-raspbian-qemu:latest /bin/echo 'Hello World'
